project_id = "gnppiredveefqbsqeuob"

[functions.send-order-email]
verify_jwt = false

[functions.send-product-order-email]
verify_jwt = false

[functions.send-cart-order-email]
verify_jwt = false

[functions.send-meeting-email]
verify_jwt = false

[functions.send-registration-notification]
verify_jwt = false

[functions.send-password-reset-notification]
verify_jwt = false

[functions.check-domain]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-email-templates]
verify_jwt = false

[functions.admin-change-password]
verify_jwt = true

[functions.generate-image]
verify_jwt = false

[functions.enhance-image]
verify_jwt = false

[functions.cleanup-temp-images]
verify_jwt = false

[functions.send-project-status-email]
verify_jwt = false