project_id = "gnppiredveefqbsqeuob"

[functions.send-order-email]
verify_jwt = false

[functions.send-product-order-email]
verify_jwt = false

[functions.send-meeting-email]
verify_jwt = false

[functions.check-domain]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-email-templates]
verify_jwt = false

